import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:share_plus/share_plus.dart';
import '../../../theme/app_theme.dart';
import '../providers/nutrition_providers.dart';

class GroceryListScreen extends ConsumerStatefulWidget {
  const GroceryListScreen({super.key});

  @override
  ConsumerState<GroceryListScreen> createState() => _GroceryListScreenState();
}

class _GroceryListScreenState extends ConsumerState<GroceryListScreen> with SingleTickerProviderStateMixin {
  late TabController _tabController;
  final List<String> _durations = ['daily', 'weekly', 'monthly'];
  
  // Local state to keep track of checked items (using name as key)
  final Map<String, bool> _checkedItems = {};

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this, initialIndex: 1); // default weekly
    _tabController.addListener(_handleTabChange);
  }

  @override
  void dispose() {
    _tabController.removeListener(_handleTabChange);
    _tabController.dispose();
    super.dispose();
  }

  void _handleTabChange() {
    if (_tabController.indexIsChanging) return;
    _loadGroceryList();
  }

  void _loadGroceryList() {
    final meals = ref.read(mealPlanProvider).meals;
    if (meals != null) {
      final dur = _durations[_tabController.index];
      ref.read(groceryListProvider.notifier).fetchGroceryList(meals, dur);
    }
  }

  void _shareGroceryList(Map<String, dynamic> data) {
    final dur = _durations[_tabController.index].toUpperCase();
    final buffer = StringBuffer();
    buffer.writeln("🛒 MY AI GYM BUDDY NUTRITION GROCERY LIST ($dur)");
    buffer.writeln("==================================================\n");

    final categories = ['Proteins', 'Vegetables', 'Grains & Cereals', 'Dairy', 'Fruits', 'Condiments & Spices'];
    for (var cat in categories) {
      if (data[cat] != null) {
        buffer.writeln("🔹 $cat:");
        final List items = data[cat];
        for (var item in items) {
          final isChecked = _checkedItems[item['name']] ?? false;
          final status = isChecked ? "[x]" : "[ ]";
          buffer.writeln("  $status ${item['name']} - ${item['quantity']}${item['unit']} (Est: ₹${item['estimated_cost_inr']})");
        }
        buffer.writeln();
      }
    }

    buffer.writeln("==================================================");
    buffer.writeln("Total Estimated Cost: ₹${data['total_estimated_cost_inr']}");
    buffer.writeln("Generated by Kinetic AI Gym Buddy Platform.");

    Share.share(buffer.toString());
  }

  @override
  Widget build(BuildContext context) {
    final profile = ref.watch(nutritionProfileProvider).profile;
    final mealState = ref.watch(mealPlanProvider);
    final groceryState = ref.watch(groceryListProvider);

    final hasMeals = mealState.meals != null;

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: AppColors.white),
          onPressed: () => context.pop(),
        ),
        title: const Text(
          'GROCERY CHECKLIST',
          style: TextStyle(color: AppColors.white, fontWeight: FontWeight.bold, letterSpacing: 1.2),
        ),
        bottom: TabBar(
          controller: _tabController,
          indicatorColor: AppColors.primaryFixed,
          labelColor: AppColors.primaryFixed,
          unselectedLabelColor: AppColors.onSurfaceVariant,
          tabs: const [
            Tab(text: 'Daily'),
            Tab(text: 'Weekly'),
            Tab(text: 'Monthly'),
          ],
        ),
      ),
      body: SafeArea(
        child: !hasMeals
            ? _buildNoMealsState()
            : groceryState.isLoading
                ? const Center(child: CircularProgressIndicator(color: AppColors.primaryFixed))
                : groceryState.groceryData == null
                    ? _buildEmptyState()
                    : _buildListContent(groceryState.groceryData!),
      ),
      floatingActionButton: groceryState.groceryData != null
          ? FloatingActionButton(
              backgroundColor: AppColors.primaryFixed,
              onPressed: () => _shareGroceryList(groceryState.groceryData!),
              child: const Icon(Icons.share, color: AppColors.onPrimaryFixed),
            )
          : null,
    );
  }

  Widget _buildNoMealsState() {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.shopping_basket_outlined, size: 70, color: AppColors.onSurfaceVariant),
            const SizedBox(height: 24),
            const Text(
              'Generate a Meal Plan First',
              style: TextStyle(color: AppColors.white, fontSize: 18, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 12),
            const Text(
              'A grocery list requires a generated diet plan to extract and sum raw ingredients.',
              textAlign: TextAlign.center,
              style: TextStyle(color: AppColors.onSurfaceVariant, fontSize: 13, height: 1.4),
            ),
            const SizedBox(height: 24),
            ElevatedButton(
              onPressed: () => context.push('/member/meal-plan'),
              style: ElevatedButton.styleFrom(
                backgroundColor: AppColors.primaryFixed,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
              ),
              child: const Text('Go to Meal Planner', style: TextStyle(color: AppColors.onPrimaryFixed)),
            )
          ],
        ),
      ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          const Icon(Icons.shopping_cart_checkout, size: 64, color: AppColors.onSurfaceVariant),
          const SizedBox(height: 16),
          const Text('No ingredients found.', style: TextStyle(color: AppColors.white)),
          const SizedBox(height: 12),
          ElevatedButton(
            onPressed: _loadGroceryList,
            style: ElevatedButton.styleFrom(backgroundColor: AppColors.primaryFixed),
            child: const Text('Generate List', style: TextStyle(color: AppColors.onPrimaryFixed)),
          )
        ],
      ),
    );
  }

  Widget _buildListContent(Map<String, dynamic> data) {
    final categories = ['Proteins', 'Vegetables', 'Grains & Cereals', 'Dairy', 'Fruits', 'Condiments & Spices'];
    final List<Widget> listWidgets = [];

    for (var cat in categories) {
      final List items = data[cat] ?? [];
      if (items.isNotEmpty) {
        // Section Header
        listWidgets.add(
          Padding(
            padding: const EdgeInsets.only(top: 20, bottom: 8, left: 16),
            child: Text(
              cat.toUpperCase(),
              style: const TextStyle(
                color: AppColors.primaryFixed,
                fontWeight: FontWeight.bold,
                fontSize: 12,
                letterSpacing: 1.5,
              ),
            ),
          ),
        );

        // Section Cards
        for (var item in items) {
          final isChecked = _checkedItems[item['name']] ?? false;
          listWidgets.add(
            Container(
              margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
              decoration: BoxDecoration(
                color: const Color(0xFF201F1F),
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: AppColors.white.withOpacity(0.03)),
              ),
              child: CheckboxListTile(
                value: isChecked,
                activeColor: AppColors.primaryFixed,
                checkColor: AppColors.onPrimaryFixed,
                title: Text(
                  item['name'],
                  style: TextStyle(
                    color: isChecked ? AppColors.onSurfaceVariant : AppColors.white,
                    fontWeight: FontWeight.bold,
                    decoration: isChecked ? TextDecoration.lineThrough : null,
                    fontSize: 14,
                  ),
                ),
                subtitle: Text(
                  'Quantity: ${item['quantity']} ${item['unit']} • Est: ₹${item['estimated_cost_inr']}',
                  style: const TextStyle(color: AppColors.onSurfaceVariant, fontSize: 12),
                ),
                onChanged: (val) {
                  setState(() {
                    _checkedItems[item['name']] = val ?? false;
                  });
                },
              ),
            ),
          );
        }
      }
    }

    // Scroll view + bottom estimated cost bar
    return Column(
      children: [
        Expanded(
          child: ListView(
            padding: const EdgeInsets.only(bottom: 24),
            children: listWidgets,
          ),
        ),
        _buildBottomCostBar(data['total_estimated_cost_inr'] ?? 0),
      ],
    );
  }

  Widget _buildBottomCostBar(int cost) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: const Color(0xFF1B1B1B),
        border: Border(top: BorderSide(color: AppColors.white.withOpacity(0.08))),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          const Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              Text('ESTIMATED BUDGET', style: TextStyle(color: AppColors.onSurfaceVariant, fontSize: 10, letterSpacing: 1.2)),
              SizedBox(height: 2),
              Text('Total Shopping Cost', style: TextStyle(color: AppColors.white, fontWeight: FontWeight.bold, fontSize: 14)),
            ],
          ),
          Text(
            '₹$cost',
            style: const TextStyle(color: AppColors.primaryFixed, fontWeight: FontWeight.bold, fontSize: 24),
          )
        ],
      ),
    );
  }
}
