# Generated by Django 3.2.25 on 2026-06-07 14:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=255, verbose_name='plan name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('duration_days', models.PositiveIntegerField(verbose_name='duration in days')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='gyms.gym')),
            ],
            options={
                'verbose_name': 'membership plan',
                'verbose_name_plural': 'membership plans',
                'db_table': 'membership_plans',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.member')),
                ('membership_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_memberships', to='memberships.membershipplan')),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'memberships',
                'db_table': 'member_memberships',
            },
        ),
        migrations.AddIndex(
            model_name='membershipplan',
            index=models.Index(fields=['gym', 'is_deleted'], name='membership__gym_id_789e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipplan',
            index=models.Index(fields=['is_active'], name='membership__is_acti_6c2cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['member', 'status'], name='member_memb_member__61bbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['start_date'], name='member_memb_start_d_a95469_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['end_date'], name='member_memb_end_dat_68a7d2_idx'),
        ),
    ]
