# Generated by Django 3.2.25 on 2026-06-12 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
        ('trainers', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('session_date', models.DateField()),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('max_capacity', models.PositiveIntegerField(default=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gyms.gym')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='trainers.trainer')),
            ],
            options={
                'db_table': 'workout_sessions',
                'ordering': ['session_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='booked', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='members.member')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='workout_sessions.workoutsession')),
            ],
            options={
                'db_table': 'session_bookings',
            },
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['gym', 'is_deleted'], name='workout_ses_gym_id_db1011_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['trainer', 'is_deleted'], name='workout_ses_trainer_b99bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['session_date'], name='workout_ses_session_10cae4_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionbooking',
            index=models.Index(fields=['session', 'status'], name='session_boo_session_829933_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionbooking',
            index=models.Index(fields=['member', 'status'], name='session_boo_member__1909bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionbooking',
            unique_together={('session', 'member')},
        ),
    ]
