# Generated by Django 3.2.25 on 2026-06-20 15:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_type', models.CharField(choices=[('GENERAL', 'General'), ('WORKOUT', 'Workout Help'), ('DIET', 'Diet & Nutrition'), ('PROGRESS', 'Progress Analysis'), ('BEGINNER', 'Beginner Guidance'), ('EXERCISE_ALT', 'Exercise Alternatives')], default='GENERAL', max_length=20)),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='gyms.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='members.member')),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fitness_center', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kb_categories', to='gyms.gym')),
            ],
            options={
                'db_table': 'ai_knowledge_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300)),
                ('summary', models.TextField(help_text='Short 1-2 sentence summary for chat responses')),
                ('content', models.TextField(help_text='Full article content')),
                ('article_type', models.CharField(choices=[('EXERCISE', 'Exercise'), ('NUTRITION', 'Nutrition'), ('WORKOUT_PLAN', 'Workout Plan'), ('RECOVERY', 'Recovery'), ('GENERAL', 'General Fitness'), ('BEGINNER_GUIDE', 'Beginner Guide')], default='GENERAL', max_length=30)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
                ('tags', models.TextField(blank=True, default='', help_text='Comma-separated tags')),
                ('muscle_groups', models.TextField(blank=True, default='', help_text='Comma-separated muscle groups')),
                ('equipment', models.TextField(blank=True, default='', help_text='Comma-separated equipment')),
                ('keywords', models.TextField(blank=True, help_text='Space-separated keywords for search')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='ai_gym_buddy.knowledgecategory')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kb_articles', to='gyms.gym')),
            ],
            options={
                'db_table': 'ai_knowledge_articles',
                'ordering': ['-is_featured', '-view_count', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_muscles', models.TextField(blank=True, default='')),
                ('secondary_muscles', models.TextField(blank=True, default='')),
                ('equipment_needed', models.TextField(blank=True, default='')),
                ('movement_pattern', models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('HINGE', 'Hinge'), ('SQUAT', 'Squat'), ('CARRY', 'Carry'), ('ROTATION', 'Rotation'), ('ISOLATION', 'Isolation'), ('COMPOUND', 'Compound')], default='COMPOUND', max_length=20)),
                ('common_mistakes', models.TextField(blank=True)),
                ('cues', models.TextField(blank=True, help_text='Coaching cues for form')),
                ('reps_range', models.CharField(blank=True, default='', max_length=20)),
                ('rest_seconds', models.PositiveSmallIntegerField(default=90)),
                ('calories_per_minute', models.FloatField(default=6.0)),
                ('alternatives', models.ManyToManyField(blank=True, help_text='Alternative exercises to this one', related_name='exercise_alternatives', to='ai_gym_buddy.KnowledgeArticle')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_data', to='ai_gym_buddy.knowledgearticle')),
            ],
            options={
                'db_table': 'ai_exercise_data',
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('context_data', models.TextField(blank=True, default='{}')),
                ('sources', models.TextField(blank=True, default='[]')),
                ('response_source', models.CharField(blank=True, choices=[('KB', 'Knowledge Base'), ('TEMPLATE', 'Template Response'), ('LLM', 'Language Model'), ('CONTEXT', 'Context Analysis')], default='KB', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_gym_buddy.aiconversation')),
            ],
            options={
                'db_table': 'ai_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('detected_intent', models.CharField(blank=True, max_length=50)),
                ('response_source', models.CharField(choices=[('KB', 'Knowledge Base'), ('TEMPLATE', 'Template Response'), ('LLM', 'Language Model'), ('CONTEXT', 'Context Analysis')], default='KB', max_length=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interaction_logs', to='gyms.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interaction_logs', to='members.member')),
            ],
            options={
                'db_table': 'ai_interaction_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgecategory',
            index=models.Index(fields=['gym', 'is_active'], name='ai_knowledg_gym_id_8487ac_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgecategory',
            index=models.Index(fields=['slug'], name='ai_knowledg_slug_f5ee56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgecategory',
            unique_together={('gym', 'slug')},
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['gym', 'article_type', 'is_active'], name='ai_knowledg_gym_id_5105ac_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['difficulty', 'is_active'], name='ai_knowledg_difficu_768673_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['category', 'is_active'], name='ai_knowledg_categor_147785_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['is_featured', 'is_active'], name='ai_knowledg_is_feat_22680a_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_messages_convers_15163f_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinteractionlog',
            index=models.Index(fields=['gym', 'member'], name='ai_interact_gym_id_146d68_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinteractionlog',
            index=models.Index(fields=['detected_intent'], name='ai_interact_detecte_9c0878_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['gym', 'member'], name='ai_conversa_gym_id_97217e_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['member', 'conversation_type'], name='ai_conversa_member__c4a401_idx'),
        ),
    ]
