# Generated by Django 3.2.25 on 2026-06-20 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
        ('ai_gym_buddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeQA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subcategory', models.CharField(blank=True, default='', max_length=100)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('keywords', models.TextField(blank=True, help_text='Space-separated keywords')),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
                ('safety_notes', models.TextField(blank=True, default='')),
                ('related_topics', models.TextField(blank=True, default='', help_text='Comma-separated topics')),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', help_text='Language code (e.g. en, es, fr)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qas', to='ai_gym_buddy.knowledgecategory')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kb_qas', to='gyms.gym')),
            ],
            options={
                'db_table': 'ai_knowledge_qas',
                'ordering': ['question'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeqa',
            index=models.Index(fields=['gym', 'category', 'is_active'], name='ai_knowledg_gym_id_7e20cf_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeqa',
            index=models.Index(fields=['language', 'is_active'], name='ai_knowledg_languag_194271_idx'),
        ),
    ]
