# Generated by Django 3.2.25 on 2026-06-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance')], max_length=20)),
                ('age', models.IntegerField()),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
                ('activity_level', models.CharField(max_length=20)),
                ('workout_days_per_week', models.IntegerField()),
                ('budget_inr', models.IntegerField()),
                ('food_preference', models.CharField(max_length=20)),
                ('allergies', models.TextField(blank=True)),
                ('medical_restrictions', models.TextField(blank=True)),
                ('bmr', models.FloatField(null=True)),
                ('tdee', models.FloatField(null=True)),
                ('target_calories', models.IntegerField(null=True)),
                ('protein_g', models.IntegerField(null=True)),
                ('carbs_g', models.IntegerField(null=True)),
                ('fat_g', models.IntegerField(null=True)),
                ('water_liters', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_profile', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='DietLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('breakfast_done', models.BooleanField(default=False)),
                ('lunch_done', models.BooleanField(default=False)),
                ('dinner_done', models.BooleanField(default=False)),
                ('snacks_done', models.BooleanField(default=False)),
                ('pre_workout_done', models.BooleanField(default=False)),
                ('post_workout_done', models.BooleanField(default=False)),
                ('calories_consumed', models.IntegerField(default=0)),
                ('protein_consumed_g', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_diet_logs', to='members.member')),
            ],
            options={
                'unique_together': {('member', 'log_date')},
            },
        ),
    ]
