# Generated by Django 3.2.25 on 2026-06-12 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, verbose_name='Employee ID')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Specialization')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Experience (Years)')),
                ('certifications', models.TextField(blank=True, null=True, verbose_name='Certifications')),
                ('joining_date', models.DateField(verbose_name='Joining Date')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salary')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('profile_image', models.TextField(blank=True, null=True, verbose_name='Profile Image URL or Base64')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='gyms.gym')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainers',
            },
        ),
        migrations.CreateModel(
            name='TrainerAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainer_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrainerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(verbose_name='Assigned Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignments', to='members.member')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='trainers.trainer')),
            ],
            options={
                'db_table': 'trainer_assignments',
            },
        ),
        migrations.AddIndex(
            model_name='trainerassignment',
            index=models.Index(fields=['trainer', 'status'], name='trainer_ass_trainer_b80f26_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerassignment',
            index=models.Index(fields=['member', 'status'], name='trainer_ass_member__afb600_idx'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['gym', 'is_deleted'], name='trainers_gym_id_8e19bb_idx'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['employee_id'], name='trainers_employe_4a14d0_idx'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['status'], name='trainers_status_316368_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainer',
            unique_together={('gym', 'employee_id')},
        ),
    ]
