# Generated by Django 3.2.25 on 2026-06-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='member_profiles/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gyms.gym')),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gym', 'is_deleted'], name='members_gym_id_836504_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['email'], name='members_email_d65d03_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone_number'], name='members_phone_n_e3a435_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status'], name='members_status_e4ea77_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['full_name'], name='members_full_na_398ca2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('gym', 'email')},
        ),
    ]
