# Generated by Django 3.2.25 on 2026-06-07 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gym_name', models.CharField(max_length=255, verbose_name='gym name')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('pincode', models.CharField(max_length=20, verbose_name='pincode')),
                ('contact_number', models.CharField(max_length=20, verbose_name='contact number')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gym_logos/', verbose_name='logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Owner of the gym', on_delete=django.db.models.deletion.PROTECT, related_name='gyms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gym',
                'verbose_name_plural': 'gyms',
                'db_table': 'gyms',
            },
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['owner', 'is_deleted'], name='gyms_owner_i_a7aec4_idx'),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['city', 'state'], name='gyms_city_7f5aee_idx'),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['gym_name'], name='gyms_gym_nam_b3145e_idx'),
        ),
    ]
