# Generated by Django 3.2.25 on 2026-06-28 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenancy', '0001_initial'),
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to='tenancy.tenant'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255, verbose_name='branch name')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('pincode', models.CharField(max_length=20, verbose_name='pincode')),
                ('contact_number', models.CharField(max_length=20, verbose_name='contact number')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='gyms.gym')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'db_table': 'branches',
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['gym', 'is_deleted'], name='branches_gym_id_bd7437_idx'),
        ),
    ]
