# Generated by Django 3.2.25 on 2026-06-13 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
        ('gyms', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=True)),
                ('completion_time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diet_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=150)),
                ('goal', models.CharField(choices=[('FAT_LOSS', 'Fat Loss'), ('MUSCLE_GAIN', 'Muscle Gain'), ('MAINTENANCE', 'Maintenance'), ('WEIGHT_GAIN', 'Weight Gain'), ('ATHLETIC_PERFORMANCE', 'Athletic Performance')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_calories', models.PositiveIntegerField()),
                ('target_protein', models.PositiveIntegerField()),
                ('target_carbs', models.PositiveIntegerField()),
                ('target_fats', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'diet_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DietPlanMeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField()),
                ('sequence_order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'diet_plan_meals',
                'ordering': ['day_number', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PROTEIN', 'Protein'), ('CARBOHYDRATE', 'Carbohydrate'), ('FAT', 'Fat'), ('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('DAIRY', 'Dairy'), ('SUPPLEMENT', 'Supplement'), ('BEVERAGE', 'Beverage')], max_length=50)),
                ('serving_size', models.CharField(max_length=50)),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fiber', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'foods',
                'ordering': ['food_name'],
            },
        ),
        migrations.CreateModel(
            name='MemberDietPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_assignments', to='trainers.trainer')),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_assignments', to='diets.dietplan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='members.member')),
            ],
            options={
                'db_table': 'member_diet_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=150)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack'), ('PRE_WORKOUT', 'Pre Workout'), ('POST_WORKOUT', 'Post Workout')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_templates', to='trainers.trainer')),
            ],
            options={
                'db_table': 'meal_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('serving_unit', models.CharField(default='g', max_length=50)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.food')),
                ('meal_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_foods', to='diets.mealtemplate')),
            ],
            options={
                'db_table': 'meal_foods',
            },
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['food_name'], name='foods_food_na_75f860_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['category'], name='foods_categor_2dc373_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['is_active', 'is_deleted'], name='foods_is_acti_211179_idx'),
        ),
        migrations.AddField(
            model_name='dietplanmeal',
            name='diet_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_meals', to='diets.dietplan'),
        ),
        migrations.AddField(
            model_name='dietplanmeal',
            name='meal_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_meals', to='diets.mealtemplate'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='trainers.trainer'),
        ),
        migrations.AddField(
            model_name='dietlog',
            name='assigned_diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='diets.memberdietplan'),
        ),
        migrations.AddField(
            model_name='dietlog',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='diets.dietplanmeal'),
        ),
        migrations.AddField(
            model_name='dietlog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to='members.member'),
        ),
        migrations.AddIndex(
            model_name='memberdietplan',
            index=models.Index(fields=['member', 'status'], name='member_diet_member__86b3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='memberdietplan',
            index=models.Index(fields=['diet_plan'], name='member_diet_diet_pl_9da79b_idx'),
        ),
        migrations.AddIndex(
            model_name='memberdietplan',
            index=models.Index(fields=['assigned_by'], name='member_diet_assigne_d101ad_idx'),
        ),
        migrations.AddIndex(
            model_name='mealtemplate',
            index=models.Index(fields=['trainer'], name='meal_templa_trainer_c1b38e_idx'),
        ),
        migrations.AddIndex(
            model_name='mealtemplate',
            index=models.Index(fields=['meal_type'], name='meal_templa_meal_ty_9cf2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='mealfood',
            index=models.Index(fields=['meal_template'], name='meal_foods_meal_te_82f435_idx'),
        ),
        migrations.AddIndex(
            model_name='mealfood',
            index=models.Index(fields=['food'], name='meal_foods_food_id_018a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='dietplanmeal',
            index=models.Index(fields=['diet_plan'], name='diet_plan_m_diet_pl_00dbaf_idx'),
        ),
        migrations.AddIndex(
            model_name='dietplanmeal',
            index=models.Index(fields=['meal_template'], name='diet_plan_m_meal_te_a113eb_idx'),
        ),
        migrations.AddIndex(
            model_name='dietplanmeal',
            index=models.Index(fields=['day_number'], name='diet_plan_m_day_num_87b5d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dietplanmeal',
            unique_together={('diet_plan', 'day_number', 'sequence_order')},
        ),
        migrations.AddIndex(
            model_name='dietplan',
            index=models.Index(fields=['trainer'], name='diet_plans_trainer_f4f165_idx'),
        ),
        migrations.AddIndex(
            model_name='dietplan',
            index=models.Index(fields=['gym', 'is_deleted'], name='diet_plans_gym_id_1b549c_idx'),
        ),
        migrations.AddIndex(
            model_name='dietplan',
            index=models.Index(fields=['goal'], name='diet_plans_goal_7481d3_idx'),
        ),
        migrations.AddIndex(
            model_name='dietplan',
            index=models.Index(fields=['status'], name='diet_plans_status_a6f8c9_idx'),
        ),
        migrations.AddIndex(
            model_name='dietlog',
            index=models.Index(fields=['member'], name='diet_logs_member__aa46b0_idx'),
        ),
        migrations.AddIndex(
            model_name='dietlog',
            index=models.Index(fields=['assigned_diet'], name='diet_logs_assigne_e84eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='dietlog',
            index=models.Index(fields=['meal'], name='diet_logs_meal_id_77c31b_idx'),
        ),
        migrations.AddIndex(
            model_name='dietlog',
            index=models.Index(fields=['created_at'], name='diet_logs_created_030e38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dietlog',
            unique_together={('assigned_diet', 'meal', 'created_at')},
        ),
    ]
