# Generated by Django 3.2.25 on 2026-06-13 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_type', models.CharField(choices=[('FRONT', 'Front'), ('SIDE', 'Side'), ('BACK', 'Back')], default='FRONT', max_length=10)),
                ('image', models.ImageField(upload_to='progress_photos/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to='members.member')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_progress_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress_photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_name', models.CharField(max_length=255)),
                ('achieved_date', models.DateField(default=django.utils.timezone.localdate)),
                ('achievement_value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_milestones', to='members.member')),
            ],
            options={
                'db_table': 'progress_milestones',
                'ordering': ['-achieved_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_kg', models.FloatField()),
                ('body_fat_percentage', models.FloatField()),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField()),
                ('chest_cm', models.FloatField(blank=True, null=True)),
                ('waist_cm', models.FloatField(blank=True, null=True)),
                ('hips_cm', models.FloatField(blank=True, null=True)),
                ('shoulders_cm', models.FloatField(blank=True, null=True)),
                ('biceps_cm', models.FloatField(blank=True, null=True)),
                ('forearms_cm', models.FloatField(blank=True, null=True)),
                ('thighs_cm', models.FloatField(blank=True, null=True)),
                ('calves_cm', models.FloatField(blank=True, null=True)),
                ('neck_cm', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='members.member')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_measurements', to='trainers.trainer')),
            ],
            options={
                'db_table': 'progress_measurements',
                'ordering': ['-recorded_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_type', models.CharField(choices=[('FAT_LOSS', 'Fat Loss'), ('MUSCLE_GAIN', 'Muscle Gain'), ('WEIGHT_GAIN', 'Weight Gain'), ('MAINTENANCE', 'Maintenance')], default='FAT_LOSS', max_length=20)),
                ('starting_weight', models.FloatField(blank=True, null=True)),
                ('starting_body_fat', models.FloatField(blank=True, null=True)),
                ('target_weight', models.FloatField(blank=True, null=True)),
                ('target_body_fat', models.FloatField(blank=True, null=True)),
                ('target_date', models.DateField()),
                ('current_progress_percentage', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACHIEVED', 'Achieved'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_goals', to='members.member')),
            ],
            options={
                'db_table': 'fitness_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='progressphoto',
            index=models.Index(fields=['member', 'photo_type'], name='progress_ph_member__fde8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='progressphoto',
            index=models.Index(fields=['uploaded_at'], name='progress_ph_uploade_908169_idx'),
        ),
        migrations.AddIndex(
            model_name='progressmilestone',
            index=models.Index(fields=['member', 'achieved_date'], name='progress_mi_member__fa8761_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progressmilestone',
            unique_together={('member', 'milestone_name')},
        ),
        migrations.AddIndex(
            model_name='progressmeasurement',
            index=models.Index(fields=['member', 'recorded_date'], name='progress_me_member__fb86b2_idx'),
        ),
        migrations.AddIndex(
            model_name='progressmeasurement',
            index=models.Index(fields=['recorded_date'], name='progress_me_recorde_8c274b_idx'),
        ),
        migrations.AddIndex(
            model_name='fitnessgoal',
            index=models.Index(fields=['member', 'status'], name='fitness_goa_member__7c0a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='fitnessgoal',
            index=models.Index(fields=['target_date'], name='fitness_goa_target__72d968_idx'),
        ),
    ]
