# Generated by Django 3.2.25 on 2026-06-07 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
        ('members', '0001_initial'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('attendance_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], default='PRESENT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gyms.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='memberships.membership')),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-attendance_date', '-check_in_time'],
            },
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_date'], name='attendance__attenda_90bebd_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['member', 'attendance_date'], name='attendance__member__4cb7c5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['gym', 'attendance_date'], name='attendance__gym_id_7fdc2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('member', 'attendance_date'), name='unique_active_attendance_per_day'),
        ),
    ]
