# Generated by Django 3.2.25 on 2026-06-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_auto_20260628_1951'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='gyms.branch'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['branch', 'attendance_date'], name='attendance__branch__cfebfa_idx'),
        ),
    ]
