# Generated by Django 3.2.25 on 2026-06-13 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_name', models.CharField(max_length=100, unique=True)),
                ('badge_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('points_reward', models.PositiveIntegerField(default=50)),
                ('criteria', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gamification_badges',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_name', models.CharField(max_length=150)),
                ('challenge_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('target_value', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reward_points', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gamification_challenges',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('WORKOUT_COMPLETION', 'Workout Completion'), ('DIET_COMPLETION', 'Diet Completion'), ('GOAL_ACHIEVEMENT', 'Goal Achievement'), ('MEMBERSHIP_RENEWAL', 'Membership Renewal'), ('CHALLENGE_COMPLETION', 'Challenge Completion'), ('BADGE_UNLOCKED', 'Badge Unlocked')], max_length=50, unique=True)),
                ('points_value', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gamification_point_rules',
            },
        ),
        migrations.CreateModel(
            name='RewardCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('points_cost', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gamification_reward_catalog',
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('streak_type', models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('WORKOUT', 'Workout'), ('DIET', 'Diet')], max_length=20)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='members.member')),
            ],
            options={
                'db_table': 'gamification_streaks',
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_spent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('redemption_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_redemptions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='members.member')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='gamification.rewardcatalog')),
            ],
            options={
                'db_table': 'gamification_reward_redemptions',
                'ordering': ['-redemption_date'],
            },
        ),
        migrations.CreateModel(
            name='RewardPointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('WORKOUT_COMPLETION', 'Workout Completion'), ('DIET_COMPLETION', 'Diet Completion'), ('GOAL_ACHIEVEMENT', 'Goal Achievement'), ('MEMBERSHIP_RENEWAL', 'Membership Renewal'), ('CHALLENGE_COMPLETION', 'Challenge Completion'), ('BADGE_UNLOCKED', 'Badge Unlocked')], max_length=50)),
                ('points_earned', models.IntegerField()),
                ('points_balance', models.PositiveIntegerField()),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='members.member')),
            ],
            options={
                'db_table': 'gamification_point_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='gamification.badge')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='members.member')),
            ],
            options={
                'db_table': 'gamification_member_badges',
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.FloatField(default=0.0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gamification.challenge')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to='members.member')),
            ],
            options={
                'db_table': 'gamification_challenge_participations',
            },
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['member', 'streak_type'], name='gamificatio_member__3ffd8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='streak',
            unique_together={('member', 'streak_type')},
        ),
        migrations.AddIndex(
            model_name='rewardpointtransaction',
            index=models.Index(fields=['member', '-created_at'], name='gamificatio_member__b26d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardpointtransaction',
            index=models.Index(fields=['activity_type', 'reference_id'], name='gamificatio_activit_329df9_idx'),
        ),
        migrations.AddIndex(
            model_name='memberbadge',
            index=models.Index(fields=['member', '-unlocked_at'], name='gamificatio_member__2372f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memberbadge',
            unique_together={('member', 'badge')},
        ),
        migrations.AddIndex(
            model_name='challengeparticipation',
            index=models.Index(fields=['member', 'challenge'], name='gamificatio_member__5c65a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeparticipation',
            unique_together={('member', 'challenge')},
        ),
    ]
