# Generated by Django 3.2.25 on 2026-06-08 10:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('attendance', '0001_initial'),
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('scan_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DUPLICATE', 'Duplicate'), ('EXPIRED', 'Expired'), ('INVALID', 'Invalid')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scan', to='attendance.attendance')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='gyms.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='members.member')),
            ],
            options={
                'db_table': 'qr_scan_logs',
            },
        ),
        migrations.CreateModel(
            name='GymQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_type', models.CharField(choices=[('STATIC', 'Static'), ('DYNAMIC', 'Dynamic')], default='DYNAMIC', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='gyms.gym')),
            ],
            options={
                'db_table': 'gym_qr_codes',
            },
        ),
        migrations.AddIndex(
            model_name='qrscanlog',
            index=models.Index(fields=['member', 'scan_time'], name='qr_scan_log_member__941faf_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanlog',
            index=models.Index(fields=['gym', 'scan_time'], name='qr_scan_log_gym_id_698906_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanlog',
            index=models.Index(fields=['scan_status'], name='qr_scan_log_scan_st_718134_idx'),
        ),
        migrations.AddIndex(
            model_name='gymqrcode',
            index=models.Index(fields=['gym', 'is_active'], name='gym_qr_code_gym_id_8d9d42_idx'),
        ),
        migrations.AddIndex(
            model_name='gymqrcode',
            index=models.Index(fields=['qr_token'], name='gym_qr_code_qr_toke_d54601_idx'),
        ),
    ]
