# Generated by Django 3.2.25 on 2026-06-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_auditlog_supportticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='details',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details_str',
            field=models.TextField(blank=True, db_column='details', default='{}'),
        ),
    ]
